/**
 * MovieReviewer | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewDto } from './reviewDto';


export interface MovieDetailsDto { 
    id: string;
    title: string;
    genre: string;
    director: string;
    plot: string;
    reviews?: Array<ReviewDto>;
}

