/**
 * MovieReviewer | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReviewDto { 
    id: string;
    rating: number;
    title: string;
    description: string;
    date: string;
    userName: string;
}

